# Generated by Django 5.0.6 on 2024-06-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entries'},
        ),
    ]
